name: test develop

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  workflow_dispatch:

jobs:
  test-develop:
    uses:
      ./.github/workflows/testing.yml
    with:
      image_suffix: develop
    secrets:
      PAT: ${{ secrets.PAT }}
